### ISSUE TITLE
Route Isn't Displayed with Local Clone

### ISSUE THREAD

**Issue by danyeaw** [Project-OSRM/osrm-frontend#47]
If I clone the project, opening index.html in Firefox shows the map as expected, but as soon as I select two points the route never shows up. It works properly on the demo server. Steps:
git clone -b gh-pages https://github.com/Project-OSRM/osrm-frontend-v2.git
cd osrm-frontend-v2
firefox index.html
Select two points, the pins display but that is all.

Also "npm install" completes successful on the master branch, but that doesn't seem to fix the routing.

**Comment by TheMarex** [comment]
You need to load it from a local http server. For that occasions I have a small script:
https://gist.github.com/TheMarex/b5a44fa78a036a42f1a2
That starts up a http server in the current directory which listens on ```https://127.0.0.1:8337```

**Comment by danyeaw** [comment]
Thanks for sharing the script, that works great to get the frontend working locally. Do you know what part of the frontend requires a httpd? I am interested in using it for a mobile routing application using cordova, but loading a httpd on the phone probably isn't a good solution.

**Comment by perliedman** [comment]
One of the primary issues is probably that the OSRM server is referred by a protocol relative URL (`//router.project-osrm.org/viaroute` rather than for example `http://router.project-osrm.org/viaroute`) which causes problem when the page is loaded from `file://`. You can fix this by overriding the `serviceUrl` option to the router instance (`L.Routing.OSRM`).

However, there are other things that break when you use `file://`, such as not being able to load things with XHR even locally without running into cross-site issues in normal browsers. I have no idea how Cordova deals with this, but I guess there must be a way to load local assets with XHR.

**Comment by danyeaw** [comment]
Thanks perliedman! Changing from a relative URL to a complete URL allows it to work properly without a httpd locally. Now I need to work on getting it working with Cordova.

**Comment by DennisOSRM** [comment]
@TheMarex Is this something we should fix, too?

**Comment by TheMarex** [comment]
@DennisOSRM nothing to fix on our side. Running from file:// is just a bad idea in general.

**Comment by DennisOSRM** [comment]
Alright, fair enough. We should add a section to the readme explaining how to run _locally_ and what dependencies that carries.
